### ISSUE TITLE
TypeError: Cannot read property 'dist-tags' of undefined

### ISSUE THREAD

**Issue by maxogden** [johnmuhl/electron-prebuilt-updater#4]
started happening two releases ago

```
2015-11-26T08:07:47.140108+00:00 app[web.1]: post headers {"host":"REMOVED.herokuapp.com","connection":"close","accept":"*/*","user-agent":"GitHub-Hookshot/333881f","x-github-event":"release","x-github-delivery":"REMOVED","content-type":"application/json","x-hub-signature":"sha1=REMOVED","x-request-id":"REMOVED","x-forwarded-for":"REMOVED","x-forwarded-proto":"https","x-forwarded-port":"443","via":"1.1 vegur","connect-time":"0","x-request-start":"1448525260945","total-route-time":"6154","content-length":"25243"}
2015-11-26T08:07:47.516719+00:00 heroku[router]: at=info method=POST path="/" host=REMOVED.herokuapp.com request_id=REMOVED fwd="REMOVED" dyno=web.1 connect=0ms service=415ms status=200 bytes=221
2015-11-26T08:07:48.208638+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'dist-tags' of undefined
2015-11-26T08:07:48.208642+00:00 app[web.1]:     at /app/index.js:124:57
2015-11-26T08:07:48.208643+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:371:17)
2015-11-26T08:07:48.208644+00:00 app[web.1]: From previous event:
2015-11-26T08:07:48.208645+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/index.js:122:10)
2015-11-26T08:07:48.208646+00:00 app[web.1]:     at doNTCallback0 (node.js:408:9)
2015-11-26T08:07:48.208647+00:00 app[web.1]:     at process._tickCallback (node.js:337:13)
2015-11-26T08:40:42.640275+00:00 heroku[web.1]: Idling
2015-11-26T08:40:42.641055+00:00 heroku[web.1]: State changed from up to down
2015-11-26T08:40:46.785958+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-11-26T08:40:49.255176+00:00 heroku[web.1]: Process exited with status 143
2015-11-26T10:34:13.423709+00:00 heroku[web.1]: Unidling
2015-11-26T10:34:13.424144+00:00 heroku[web.1]: State changed from down to starting
2015-11-26T10:34:15.219275+00:00 heroku[web.1]: Starting process with command `npm start`
2015-11-26T10:34:18.817342+00:00 app[web.1]: 
2015-11-26T10:34:18.817352+00:00 app[web.1]: > electron-prebuilt-updater@0.3.1 start /app
2015-11-26T10:34:18.817354+00:00 app[web.1]: > node index.js
2015-11-26T10:34:18.817355+00:00 app[web.1]: 
```

**Comment by johnmuhl** [comment]
Looks like using the npm API to `dist-tags add electron-prebuilt@latest` actually erases the latest tag instead of adding it (hence the cannot find property and bad installs). 9b8f9f7 uses the npm CLI instead.

**Comment by maxogden** [comment]
ahhh nice catch. will deploy fix now!

**Comment by maxogden** [comment]
ok deployed 0.4.1, will keep a watchful eye on it during the next release. thanks for the quick fix

cc @zcbenz
